### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount" : 12345
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "0391780b08b14f5bafdf1283cc1e7e6f",
  "accountNumber": "1000000000",
  "amount" : 12345
}

### query transaction
GET http://localhost:8080/transaction/a03f2eed3d4a49279a8281460a1d5779